name: Deploy HTML

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: "unnecessary"

    - name: Adding Known Hosts
      run: ssh-keyscan -p 22 -H 160.250.92.110 >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        rsync -avz --delete ./ ubuntu@160.250.92.110:/var/www/dkm01.asiadt.xyz